# Generated by Django 4.2.5 on 2023-09-11 02:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정일자"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("last_name", models.CharField(max_length=8, verbose_name="성")),
                ("first_name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "org_name",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="소속명"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="직함"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        max_length=128,
                        region=None,
                        verbose_name="휴대전화번호",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="이메일주소"
                    ),
                ),
                (
                    "thread",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.socialthread",
                        verbose_name="스레드",
                        editable=False,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "프로필",
                "verbose_name_plural": "프로필 목록",
                "db_table": "profile",
            },
        ),
    ]
