# Generated by Django 4.2.5 on 2023-09-11 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="own_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유자",
            ),
            preserve_default=False,
        ),
    ]
