# Generated by Django 4.2.5 on 2023-09-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0002_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_representative',
            field=models.BooleanField(db_index=True, default=False, verbose_name='대표 프로필 여부'),
        ),
    ]
