# Generated by Django 4.2.5 on 2023-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identify", "0004_profile_profile_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img_url",
            field=models.URLField(
                blank=True,
                default="https://picsum.photos/340/189",
                max_length=720,
                verbose_name="프로필 이미지 URL",
            ),
        ),
    ]
