# Generated by Django 4.2.5 on 2023-09-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0005_alter_profile_profile_img_url'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='profile',
            index_together={('org_name', 'job_title')},
        ),
    ]
