# Generated by Django 4.2.5 on 2023-09-11 02:20

import autoslug.fields
from django.db import migrations, models
import slugify


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정일자')),
                ('text', models.CharField(db_index=True, max_length=32)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='text', slugify=slugify.slugify)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그목록',
                'db_table': 'tag',
            },
        ),
    ]
