# Generated by Django 4.2.5 on 2023-09-11 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_profile_is_representative'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_through', to='identify.profile', verbose_name='프로필 정보'),
        ),
    ]
