# Generated by Django 4.2.5 on 2023-09-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communityprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner_img_url',
            field=models.URLField(blank=True, default='https://picsum.photos/900/292', max_length=256, verbose_name='배너 이미지 url'),
        ),
    ]
