# Generated by Django 4.2.5 on 2023-09-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0004_profile_profile_img_url'),
        ('community', '0003_alter_community_banner_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityprofile',
            options={'verbose_name': '커뮤니티 프로필', 'verbose_name_plural': '커뮤니티 프로필 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='communityprofile',
            unique_together={('community', 'profile')},
        ),
        migrations.AlterModelTable(
            name='communityprofile',
            table='community_to_profile',
        ),
    ]
