# Generated by Django 4.2.5 on 2023-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_alter_communityprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(
                db_index=True, max_length=720, verbose_name="커뮤니티 이름"
            ),
        ),
    ]
