# Generated by Django 4.2.5 on 2023-09-11 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정일자')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted At')),
                ('body', models.TextField(blank=True, db_index=True, default='', verbose_name='내용')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='own_threads', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('tags', models.ManyToManyField(to='meta.tag', verbose_name='관련태그목록')),
            ],
            options={
                'verbose_name': '스레드',
                'verbose_name_plural': '스레드 목록',
                'db_table': 'social_thread',
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정일자')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted At')),
                ('body', models.TextField(blank=True, db_index=True, default='', verbose_name='내용')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='own_comments', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('tags', models.ManyToManyField(to='meta.tag', verbose_name='관련태그목록')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialthread', verbose_name='스레드')),
            ],
            options={
                'verbose_name': '코멘트',
                'verbose_name_plural': '코멘트 목록',
                'db_table': 'social_comment',
            },
        ),
    ]
