# Generated by Django 4.2.5 on 2023-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcomment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meta.tag', verbose_name='관련태그목록'),
        ),
        migrations.AlterField(
            model_name='socialthread',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meta.tag', verbose_name='관련태그목록'),
        ),
    ]
